spring:
   redis:
      hosts: ${SPRING_REDIS_HOSTS}
      host: ${SPRING_REDIS_HOST}
      password: ${SPRING_REDIS_PASSWORD}
      database: ${SPRING_REDIS_DATABASE}
   main:
    allow-bean-definition-overriding: true
   jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss